version: 2

jobs:
  build:
    working_directory: /reedflinch.io
    docker:
      - image: reedflinch/hugo:0.37

    steps:
      - checkout

      - run:
          name: Init
          command: |
            git submodule init
            git submodule update

      - run:
          name: Build
          command: HUGO_ENV=production hugo -v

      - persist_to_workspace:
          root: /reedflinch.io
          paths:
            - public/*

  infra:
    working_directory: /reedflinch.io
    docker:
      - image: reedflinch/terraform:0.11.2

    steps:
      - checkout

      - run:
          name: Terraform
          command: ./deploy/infra.sh

  deploy:
    working_directory: /reedflinch.io
    docker:
      - image: reedflinch/terraform:0.11.2

    steps:
      - checkout

      - attach_workspace:
          at: /reedflinch.io

      - run:
          name: S3
          command: ./deploy/site.sh

workflows:
  version: 2
  build:
    jobs:
      - build
      - infra:
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
            - infra
          filters:
            branches:
              only: master
