version: 2

# CircleCI configuration file reference:
# https://circleci.com/docs/2.0/configuration-reference/

jobs:
  build:
    working_directory: /reedflinch.io
    docker:
      - image: reedflinch/hugo

    steps:
      - checkout

      - run:
          name: Build
          command: |
            mkdir -p content
            hugo -v

# Workflows reference:
# https://circleci.com/docs/2.0/workflows/
workflows:
  version: 2
  build:
    jobs:
      - build:
